/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsManageRouteImport } from './routes/students-manage'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as SocialPortfolioRouteImport } from './routes/social-portfolio'
import { Route as MyTestsRouteImport } from './routes/my-tests'
import { Route as MyResultsRouteImport } from './routes/my-results'
import { Route as MyReportRouteImport } from './routes/my-report'
import { Route as MyProfileRouteImport } from './routes/my-profile'
import { Route as MyClubsRouteImport } from './routes/my-clubs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CouncilRouteImport } from './routes/council'
import { Route as ClubsRouteImport } from './routes/clubs'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIdRouteImport } from './routes/test.$id'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as ClubsIdRouteImport } from './routes/clubs.$id'

const StudentsManageRoute = StudentsManageRouteImport.update({
  id: '/students-manage',
  path: '/students-manage',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialPortfolioRoute = SocialPortfolioRouteImport.update({
  id: '/social-portfolio',
  path: '/social-portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTestsRoute = MyTestsRouteImport.update({
  id: '/my-tests',
  path: '/my-tests',
  getParentRoute: () => rootRouteImport,
} as any)
const MyResultsRoute = MyResultsRouteImport.update({
  id: '/my-results',
  path: '/my-results',
  getParentRoute: () => rootRouteImport,
} as any)
const MyReportRoute = MyReportRouteImport.update({
  id: '/my-report',
  path: '/my-report',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/my-profile',
  path: '/my-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MyClubsRoute = MyClubsRouteImport.update({
  id: '/my-clubs',
  path: '/my-clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CouncilRoute = CouncilRouteImport.update({
  id: '/council',
  path: '/council',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubsRoute = ClubsRouteImport.update({
  id: '/clubs',
  path: '/clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIdRoute = TestIdRouteImport.update({
  id: '/test/$id',
  path: '/test/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
} as any)
const ClubsIdRoute = ClubsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClubsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/council': typeof CouncilRoute
  '/dashboard': typeof DashboardRoute
  '/my-clubs': typeof MyClubsRoute
  '/my-profile': typeof MyProfileRoute
  '/my-report': typeof MyReportRoute
  '/my-results': typeof MyResultsRoute
  '/my-tests': typeof MyTestsRoute
  '/social-portfolio': typeof SocialPortfolioRoute
  '/students': typeof StudentsRouteWithChildren
  '/students-manage': typeof StudentsManageRoute
  '/clubs/$id': typeof ClubsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/test/$id': typeof TestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/council': typeof CouncilRoute
  '/dashboard': typeof DashboardRoute
  '/my-clubs': typeof MyClubsRoute
  '/my-profile': typeof MyProfileRoute
  '/my-report': typeof MyReportRoute
  '/my-results': typeof MyResultsRoute
  '/my-tests': typeof MyTestsRoute
  '/social-portfolio': typeof SocialPortfolioRoute
  '/students': typeof StudentsRouteWithChildren
  '/students-manage': typeof StudentsManageRoute
  '/clubs/$id': typeof ClubsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/test/$id': typeof TestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/clubs': typeof ClubsRouteWithChildren
  '/council': typeof CouncilRoute
  '/dashboard': typeof DashboardRoute
  '/my-clubs': typeof MyClubsRoute
  '/my-profile': typeof MyProfileRoute
  '/my-report': typeof MyReportRoute
  '/my-results': typeof MyResultsRoute
  '/my-tests': typeof MyTestsRoute
  '/social-portfolio': typeof SocialPortfolioRoute
  '/students': typeof StudentsRouteWithChildren
  '/students-manage': typeof StudentsManageRoute
  '/clubs/$id': typeof ClubsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/test/$id': typeof TestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/auth'
    | '/clubs'
    | '/council'
    | '/dashboard'
    | '/my-clubs'
    | '/my-profile'
    | '/my-report'
    | '/my-results'
    | '/my-tests'
    | '/social-portfolio'
    | '/students'
    | '/students-manage'
    | '/clubs/$id'
    | '/students/$id'
    | '/test/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/auth'
    | '/clubs'
    | '/council'
    | '/dashboard'
    | '/my-clubs'
    | '/my-profile'
    | '/my-report'
    | '/my-results'
    | '/my-tests'
    | '/social-portfolio'
    | '/students'
    | '/students-manage'
    | '/clubs/$id'
    | '/students/$id'
    | '/test/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/auth'
    | '/clubs'
    | '/council'
    | '/dashboard'
    | '/my-clubs'
    | '/my-profile'
    | '/my-report'
    | '/my-results'
    | '/my-tests'
    | '/social-portfolio'
    | '/students'
    | '/students-manage'
    | '/clubs/$id'
    | '/students/$id'
    | '/test/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  ClubsRoute: typeof ClubsRouteWithChildren
  CouncilRoute: typeof CouncilRoute
  DashboardRoute: typeof DashboardRoute
  MyClubsRoute: typeof MyClubsRoute
  MyProfileRoute: typeof MyProfileRoute
  MyReportRoute: typeof MyReportRoute
  MyResultsRoute: typeof MyResultsRoute
  MyTestsRoute: typeof MyTestsRoute
  SocialPortfolioRoute: typeof SocialPortfolioRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  StudentsManageRoute: typeof StudentsManageRoute
  TestIdRoute: typeof TestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students-manage': {
      id: '/students-manage'
      path: '/students-manage'
      fullPath: '/students-manage'
      preLoaderRoute: typeof StudentsManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-portfolio': {
      id: '/social-portfolio'
      path: '/social-portfolio'
      fullPath: '/social-portfolio'
      preLoaderRoute: typeof SocialPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tests': {
      id: '/my-tests'
      path: '/my-tests'
      fullPath: '/my-tests'
      preLoaderRoute: typeof MyTestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-results': {
      id: '/my-results'
      path: '/my-results'
      fullPath: '/my-results'
      preLoaderRoute: typeof MyResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-report': {
      id: '/my-report'
      path: '/my-report'
      fullPath: '/my-report'
      preLoaderRoute: typeof MyReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-profile': {
      id: '/my-profile'
      path: '/my-profile'
      fullPath: '/my-profile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-clubs': {
      id: '/my-clubs'
      path: '/my-clubs'
      fullPath: '/my-clubs'
      preLoaderRoute: typeof MyClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubs': {
      id: '/clubs'
      path: '/clubs'
      fullPath: '/clubs'
      preLoaderRoute: typeof ClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/council': {
      id: '/council'
      path: '/council'
      fullPath: '/council'
      preLoaderRoute: typeof CouncilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/$id': {
      id: '/test/$id'
      path: '/test/$id'
      fullPath: '/test/$id'
      preLoaderRoute: typeof TestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/clubs/$id': {
      id: '/clubs/$id'
      path: '/$id'
      fullPath: '/clubs/$id'
      preLoaderRoute: typeof ClubsIdRouteImport
      parentRoute: typeof ClubsRoute
    }
  }
}

interface StudentsRouteChildren {
  StudentsIdRoute: typeof StudentsIdRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

interface ClubsRouteChildren {
  ClubsIdRoute: typeof ClubsIdRoute
}

const ClubsRouteChildren: ClubsRouteChildren = {
  ClubsIdRoute: ClubsIdRoute,
}

const ClubsRouteWithChildren = ClubsRoute._addFileChildren(ClubsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  ClubsRoute: ClubsRouteWithChildren,
  CouncilRoute: CouncilRoute,
  DashboardRoute: DashboardRoute,
  MyClubsRoute: MyClubsRoute,
  MyProfileRoute: MyProfileRoute,
  MyReportRoute: MyReportRoute,
  MyResultsRoute: MyResultsRoute,
  MyTestsRoute: MyTestsRoute,
  SocialPortfolioRoute: SocialPortfolioRoute,
  StudentsRoute: StudentsRouteWithChildren,
  StudentsManageRoute: StudentsManageRoute,
  TestIdRoute: TestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
